package com.health_insurance.phm_processes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Reminder Notification")
@org.kie.api.definition.type.Description("Reminder to be sent if task not soft completed by given period of time.")
public class Reminder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Description("Address where to send the reminder message.")
	@org.kie.api.definition.type.Label("eMail Address")
	private java.lang.String address;
	@org.kie.api.definition.type.Description("Subject of the reminder message.")
	@org.kie.api.definition.type.Label("Subject")
	private java.lang.String subject;
	@org.kie.api.definition.type.Description("Text of the reminder.")
	@org.kie.api.definition.type.Label("Body")
	private java.lang.String body;

	@org.kie.api.definition.type.Description(value = "eMail address to use in the From field.")
	@org.kie.api.definition.type.Label(value = "From eMail address")
	private java.lang.String from;

	public Reminder() {
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public java.lang.String getBody() {
		return this.body;
	}

	public void setBody(java.lang.String body) {
		this.body = body;
	}

	public java.lang.String getFrom() {
		return this.from;
	}

	public void setFrom(java.lang.String from) {
		this.from = from;
	}

	public Reminder(java.lang.String address, java.lang.String subject,
			java.lang.String body, java.lang.String from) {
		this.address = address;
		this.subject = subject;
		this.body = body;
		this.from = from;
	}

}