package com.health_insurance.phm_processes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Reminder Notification")
@org.kie.api.definition.type.Description("Reminder to be sent if task not soft completed by given period of time.")
public class Reminder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Description(value = "Address where to send the reminder message.")
	@org.kie.api.definition.type.Label(value = "eMail Address")
	private java.lang.String address;
	@org.kie.api.definition.type.Description(value = "Subject of the reminder message.")
	@org.kie.api.definition.type.Label(value = "Subject")
	private java.lang.String subject;
	@org.kie.api.definition.type.Description(value = "Text of the reminder.")
	@org.kie.api.definition.type.Label(value = "Body")
	private java.lang.String body;

	public Reminder() {
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public java.lang.String getBody() {
		return this.body;
	}

	public void setBody(java.lang.String body) {
		this.body = body;
	}

	public Reminder(java.lang.String address, java.lang.String subject,
			java.lang.String body) {
		this.address = address;
		this.subject = subject;
		this.body = body;
	}

}