package com.health_insurance.phm_processes;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Response")
@org.kie.api.definition.type.Description("Response from a REST API Call.")
public class Response implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Task Actor Assignment")
	private com.health_insurance.phm_processes.TaskActorAssignment assignment;
	@org.kie.api.definition.type.Label(value = "Reminder")
	private com.health_insurance.phm_processes.Reminder reminder;

	public Response() {
	}

	public com.health_insurance.phm_processes.TaskActorAssignment getAssignment() {
		return this.assignment;
	}

	public void setAssignment(
			com.health_insurance.phm_processes.TaskActorAssignment assignment) {
		this.assignment = assignment;
	}

	public com.health_insurance.phm_processes.Reminder getReminder() {
		return this.reminder;
	}

	public void setReminder(com.health_insurance.phm_processes.Reminder reminder) {
		this.reminder = reminder;
	}

	public Response(
			com.health_insurance.phm_processes.TaskActorAssignment assignment,
			com.health_insurance.phm_processes.Reminder reminder) {
		this.assignment = assignment;
		this.reminder = reminder;
	}

}